server {
    listen PORT_PLACEHOLDER;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/css application/javascript application/json;

    __API_PROXY__

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|svg|ico|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
